// Code generated by mockery. DO NOT EDIT.

package mocks

import (
	"Weather-API-Application/internal/model"

	"github.com/stretchr/testify/mock"
)

// MockWeatherService is an autogenerated mock type for the WeatherService type
type MockWeatherService struct {
	mock.Mock
}

// FetchWeatherForCity provides a mock function with given fields: city
func (_m *MockWeatherService) FetchWeatherForCity(city string) (*model.Weather, error, int) {
	ret := _m.Called(city)

	var r0 *model.Weather
	if rf, ok := ret.Get(0).(func(string) *model.Weather); ok {
		r0 = rf(city)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*model.Weather)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(city)
	} else {
		r1 = ret.Error(1)
	}

	var r2 int
	if rf, ok := ret.Get(2).(func(string) int); ok {
		r2 = rf(city)
	} else {
		r2 = ret.Get(2).(int)
	}

	return r0, r1, r2
}
